---

- include_tasks: install.yml  # noqa name[missing]

- include_tasks: configure.yml  # noqa name[missing]

- include_tasks: csr.yml  # noqa name[missing]

- include_tasks: sign.yml  # noqa name[missing]

- include_tasks: renew.yml  # noqa name[missing]

- include_tasks: revoke.yml  # noqa name[missing]

- include_tasks: convert.yml  # noqa name[missing]

- include_tasks: dh.yml  # noqa name[missing]
  when: easyrsa_generate_dh | bool

- include_tasks: download.yml  # noqa name[missing]
  when:
    - easyrsa_download | length
      or easyrsa_download_pki | bool

- name: Register the role as run
  set_fact:
    easyrsa_role_run: true
