---

- name: Renew certificates
  command: >-
    easyrsa
      {{ '--passout=pass:' + _easyrsa__cert.pass | string
         if _easyrsa__cert.pass | default(None)
         else ''
      }}
      renew
      {{ _easyrsa__cert.name }}
      {{ 'nopass' if not _easyrsa__cert.pass | default(None) else '' }}
  args:
    creates: "{{ easyrsa_pki_dir }}/renewed/issued/{{ _easyrsa__cert.name }}.crt"
  environment:
    EASYRSA_REQ_CN: "{{ _easyrsa__cert.cn | d(_easyrsa__cert.name, true) }}"
  loop: "{{ easyrsa_renew }}"
  loop_control:
    loop_var: _easyrsa__cert
  register: _result
  changed_when: _result is not failed
  tags: molecule-idempotence-notest
  no_log: "{{ lookup('ansible.builtin.env', 'MOLECULE_FILE') is falsy }}"

- name: Revoke renewed certificates
  command: >-
    easyrsa revoke-renewed "{{ _easyrsa__cert.name }}" "{{ _easyrsa__cert.reason | d('') }}"
  args:
    removes: "{{ easyrsa_pki_dir }}/renewed/issued/{{ _easyrsa__cert.name }}.crt"
  loop: "{{ easyrsa_revoke_old }}"
  tags: molecule-idempotence-notest
  loop_control:
    loop_var: _easyrsa__cert
  notify: easyrsa-regen-crl
  register: _easyrsa_crl_regeneration_needed_due_to_revoke_renewed
