---

- name: Prepare
  hosts: all
  vars_files:
    - ../../defaults/main.yml
    - vars/common.yml
    - vars/case1.yml
    - vars/revoke.yml
  tasks:
    - name: Delete files used by the tests in case they already exist in the system
      file:
        path: "{{ _easyrsa__path }}"
        state: absent
      loop: "{{ q('ansible.builtin.varnames', 'easyrsa(?!_conf_).*_dir.*')
                + q('ansible.builtin.varnames', 'easyrsa(?!_conf_).*_path.*')
                + q('ansible.builtin.varnames', 'easyrsa(?!_conf_).*_file.*')
             }}"
      loop_control:
        loop_var: _easyrsa__path
      delegate_to: localhost
